[theme]
# Solo dejamos el color de acento. Al NO definir el resto, 
# Streamlit habilita el switch de Light/Dark para el usuario.
primaryColor = "#005BAA"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = true

[client]
# 'developer' es vital para que el menú de hamburguesa no sea 'minimal'
toolbarMode = "developer"
showSidebarNavigation = true
