[theme]
# Solo dejamos el color primario para los acentos (botones/links)
primaryColor = "#005BAA"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = true

[client]
# 'developer' asegura que el menú de hamburguesa muestre todas las opciones
toolbarMode = "developer"
